<?php

use Illuminate\Database\Seeder;

final class CargosTableSeeder extends Seeder
{
    public function run()
    {
        $cargos = [
            'Acetylene',
            'Acid',
            'Air conditioners',
            'Ammunition',
            'Apples',
            'Arsenic',
            'Atlantic cod fillets',
            'Barley',
            'Beef',
            'Beverages',
            'Brake fluid',
            'Calcium',
            'Canned beef',
            'Car parts',
            'Carrots',
            'Cars',
            'Cauliflower',
            'Caviar',
            'Cement',
            'Cheese',
            'Chemicals',
            'Chicken meat',
            'Chlorine',
            'Clothes',
            'Coal',
            'Concrete',
            'Contamin',
            'Cottage cheese',
            'Curtains',
            'Cyanide',
            'Diesel',
            'Digger 1000',
            'Digger 500',
            'Diggers',
            'Disinfectant',
            'Driller',
            'Driller D-50',
            'Dry milk',
            'Dynamite',
            'Electrical wiring',
            'Electronics',
            'Empty barrels',
            'Empty pallets',
            'Excavator',
            'Explosives',
            'Fertilizer',
            'Fireworks',
            'Fish fingers',
            'Floor panels',
            'Flour',
            'Flourine',
            'Forklifts',
            'Fresh fish',
            'Frozen foods',
            'Frozen hake',
            'Fuel tanker',
            'Furniture',
            'Garlic',
            'Gas line pipes',
            'Glass panels',
            'Grass rolls',
            'Gravel',
            'Guard rails',
            'Heavy metals',
            'Helicopter',
            'Hot chemicals',
            'Ibc containers',
            'Ice cream',
            'Iron pipes',
            'Kerosene',
            'Lamb stomachs',
            'Large tubes',
            'Lead',
            'Liquefied petroleum gas',
            'Live cattle',
            'Liver paste',
            'Logs',
            'Low bed semi-trailers',
            'Lumber',
            'Luxury suv',
            'Magnesium',
            'Meat',
            'Medical supplies',
            'Mercuric chloride',
            'Milk',
            'Motor oil',
            'Neon',
            'Nitrocellulose',
            'Nitrogen',
            'Office paper',
            'Oil',
            'Oil filters',
            'Onions',
            'Oranges',
            'Ore',
            'Packaged food',
            'Packed glass',
            'Pears',
            'Peas',
            'Pesticide',
            'Pet food',
            'Petrol',
            'Plastic film rolls',
            'Plastic granules',
            'Plumbing supplies',
            'Pork',
            'Pot flowers',
            'Potassium',
            'Potatoes',
            'Potassium hydroxide',
            'Pressure tank',
            'Radiators',
            'Reflective posts',
            'Reservoir tank',
            'Rice',
            'Roller dyno cc',
            'Rubber tyres',
            'Rye',
            'Salmon fillets',
            'Sand',
            'Sausages',
            'Sawdust panels',
            'Scaffolding',
            'Scania trucks',
            'Scrap metals',
            'Sheep wool',
            'Smoked eel',
            'Smoked sprats',
            'Sodium',
            'Sodium hydroxide',
            'Sugar',
            'Sulfuric acid',
            'Tableware',
            'Tomatoes',
            'Toys',
            'Tracks',
            'Tractor rs 666',
            'Tractors',
            'Transmission',
            'Truck rims',
            'Truck tyres',
            'Used packaging',
            'Used plastics',
            'Ventilation tube',
            'Vinegar',
            'Volvo trucks',
            'Wall panels',
            'Wheat',
            'White phosphorous',
            'Wind turbine tower',
            'Wood bark',
            'Wood shavings',
            'Wooden beams',
            'Yacht',
            'Yoghurt',
        ];

        DB::table('cargos')->insert(collect($cargos)->map(function (string $cargo) {
            return ['name' => $cargo];
        })->toArray());
    }
}
