<?php

use App\Models\Country;
use App\Models\Game;
use App\Models\Location;
use App\Models\Map;
use App\Support\Enum\MapType;
use Illuminate\Database\Seeder;

class LocationsSeeder extends Seeder
{
    public function run()
    {
        collect($this->getMatrix())->each(function (array $gameData, string $gameName) {
            $game = Game::create(['name' => $gameName]);

            collect($gameData['maps'])->each(function (array $mapData, string $mapName) use ($game) {
                $map = new Map([
                    'name' => $mapName,
                    'type' => $mapData['type'],
                ]);
                $map->game()->associate($game)->save();

                collect($mapData['locations'])->each(function (array $locationData) use ($map) {
                    $location = new Location(['name' => $locationData['name']]);
                    $location->country()->associate($this->getCountry($locationData['country']));
                    $location->map()->associate($map);
                    $location->save();
                });
            });
        });
    }

    private function getCountry(string $name): Country
    {
        static $countryCache = [];

        if (isset($countryCache[$name])) {
            return $countryCache[$name];
        }

        $country = Country::firstOrCreate(['name' => $name]);

        $countryCache[$name] = $country;

        return $country;
    }

    private function getMatrix(): array
    {
        return [
            'Euro Truck Simulator 2' => [
                // Source: http://truck-simulator.wikia.com/wiki/List_of_Cities_in_Euro_Truck_Simulator_2
                'maps' => [
                    'Default' => [
                        'type' => MapType::DEFAULT,
                        'locations' => [
                            ['name' => 'Aberdeen', 'country' => 'United Kingdom'],
                            ['name' => 'Amsterdam', 'country' => 'Netherlands'],
                            ['name' => 'Berlin', 'country' => 'Germany'],
                            ['name' => 'Bern', 'country' => 'Switzerland'],
                            ['name' => 'Birmingham', 'country' => 'United Kingdom'],
                            ['name' => 'Bratislava', 'country' => 'Slovakia'],
                            ['name' => 'Bremen', 'country' => 'Germany'],
                            ['name' => 'Brussels', 'country' => 'Belgium'],
                            ['name' => 'Brno', 'country' => 'Czech Republic'],
                            ['name' => 'Calais', 'country' => 'France'],
                            ['name' => 'Cambridge', 'country' => 'United Kingdom'],
                            ['name' => 'Cardiff', 'country' => 'United Kingdom'],
                            ['name' => 'Carlisle', 'country' => 'United Kingdom'],
                            ['name' => 'Dijon', 'country' => 'France'],
                            ['name' => 'Dortmund', 'country' => 'Germany'],
                            ['name' => 'Dover', 'country' => 'United Kingdom'],
                            ['name' => 'Dresden', 'country' => 'Germany'],
                            ['name' => 'Duisburg', 'country' => 'Germany'],
                            ['name' => 'Düsseldorf', 'country' => 'Germany'],
                            ['name' => 'Edinburgh', 'country' => 'United Kingdom'],
                            ['name' => 'Erfurt', 'country' => 'Germany'],
                            ['name' => 'Felixstowe', 'country' => 'United Kingdom'],
                            ['name' => 'Frankfurt am Main', 'country' => 'Germany'],
                            ['name' => 'Genève', 'country' => 'Switzerland'],
                            ['name' => 'Glasgow', 'country' => 'United Kingdom'],
                            ['name' => 'Graz', 'country' => 'Austria'],
                            ['name' => 'Grimsby', 'country' => 'United Kingdom'],
                            ['name' => 'Groningen', 'country' => 'Netherlands'],
                            ['name' => 'Hamburg', 'country' => 'Germany'],
                            ['name' => 'Hannover', 'country' => 'Germany'],
                            ['name' => 'Innsbruck', 'country' => 'Austria'],
                            ['name' => 'Kassel', 'country' => 'Germany'],
                            ['name' => 'Kiel', 'country' => 'Germany'],
                            ['name' => 'Klagenfurt am Wörthersee', 'country' => 'Austria'],
                            ['name' => 'Köln', 'country' => 'Germany'],
                            ['name' => 'Leipzig', 'country' => 'Germany'],
                            ['name' => 'Liège', 'country' => 'Belgium'],
                            ['name' => 'Lille', 'country' => 'France'],
                            ['name' => 'Linz', 'country' => 'Austria'],
                            ['name' => 'Liverpool', 'country' => 'United Kingdom'],
                            ['name' => 'London', 'country' => 'United Kingdom'],
                            ['name' => 'Luxembourg', 'country' => 'Luxembourg'],
                            ['name' => 'Lyon', 'country' => 'France'],
                            ['name' => 'Magdeburg', 'country' => 'Germany'],
                            ['name' => 'Manchester', 'country' => 'United Kingdom'],
                            ['name' => 'Mannheim', 'country' => 'Germany'],
                            ['name' => 'Metz', 'country' => 'France'],
                            ['name' => 'Milano', 'country' => 'Italy'],
                            ['name' => 'München', 'country' => 'Germany'],
                            ['name' => 'Newcastle-upon-Tyne', 'country' => 'United Kingdom'],
                            ['name' => 'Nürnberg', 'country' => 'Germany'],
                            ['name' => 'Osnabrück', 'country' => 'Germany'],
                            ['name' => 'Paris', 'country' => 'France'],
                            ['name' => 'Plymouth', 'country' => 'United Kingdom'],
                            ['name' => 'Poznań', 'country' => 'Poland'],
                            ['name' => 'Praha', 'country' => 'Czech Republic'],
                            ['name' => 'Reims', 'country' => 'France'],
                            ['name' => 'Rostock', 'country' => 'Germany'],
                            ['name' => 'Rotterdam', 'country' => 'Netherlands'],
                            ['name' => 'Salzburg', 'country' => 'Austria'],
                            ['name' => 'Sheffield', 'country' => 'United Kingdom'],
                            ['name' => 'Southampton', 'country' => 'United Kingdom'],
                            ['name' => 'Strasbourg', 'country' => 'France'],
                            ['name' => 'Stuttgart', 'country' => 'Germany'],
                            ['name' => 'Swansea', 'country' => 'United Kingdom'],
                            ['name' => 'Szczecin', 'country' => 'Poland'],
                            ['name' => 'Torino', 'country' => 'Italy'],
                            ['name' => 'Venezia', 'country' => 'Italy'],
                            ['name' => 'Verona', 'country' => 'Italy'],
                            ['name' => 'Wien', 'country' => 'Austria'],
                            ['name' => 'Wrocław', 'country' => 'Poland'],
                            ['name' => 'Zürich', 'country' => 'Switzerland'],
                        ],
                    ],
                    'Viva la France !' => [
                        'type' => MapType::DLC,
                        'locations' => [
                            ['name' => 'Le Mans', 'country' => 'France'],
                            ['name' => 'Le Havre', 'country' => 'France'],
                            ['name' => 'La Rochelle', 'country' => 'France'],
                            ['name' => 'Golfech', 'country' => 'France'],
                            ['name' => 'Brest', 'country' => 'France'],
                            ['name' => 'Bordeaux', 'country' => 'France'],
                            ['name' => 'Bourges', 'country' => 'France'],
                            ['name' => 'Civaux', 'country' => 'France'],
                            ['name' => 'Clermont-Ferrand', 'country' => 'France'],
                            ['name' => 'Paluel', 'country' => 'France'],
                            ['name' => 'Montpellier', 'country' => 'France'],
                            ['name' => 'Nantes', 'country' => 'France'],
                            ['name' => 'Nice', 'country' => 'France'],
                            ['name' => 'Limoges', 'country' => 'France'],
                            ['name' => 'Marseille', 'country' => 'France'],
                            ['name' => 'Saint-Alban-du-Rhône', 'country' => 'France'],
                            ['name' => 'Saint-Laurent', 'country' => 'France'],
                            ['name' => 'Rennes', 'country' => 'France'],
                            ['name' => 'Roscoff', 'country' => 'France'],
                            ['name' => 'Toulouse', 'country' => 'France'],
                        ],
                    ],
                    'Scandinavia' => [
                        'type' => MapType::DLC,
                        'locations' => [
                            ['name' => 'Kristiansand', 'country' => 'Norway'],
                            ['name' => 'København', 'country' => 'Denmark'],
                            ['name' => 'Karlskrona', 'country' => 'Sweden'],
                            ['name' => 'Kalmar', 'country' => 'Sweden'],
                            ['name' => 'Jönköping', 'country' => 'Sweden'],
                            ['name' => 'Gedser', 'country' => 'Denmark'],
                            ['name' => 'Frederikshavn', 'country' => 'Denmark'],
                            ['name' => 'Göteborg', 'country' => 'Sweden'],
                            ['name' => 'Helsingborg', 'country' => 'Sweden'],
                            ['name' => 'Hirtshals', 'country' => 'Denmark'],
                            ['name' => 'Aalborg', 'country' => 'Denmark'],
                            ['name' => 'Bergen', 'country' => 'Norway'],
                            ['name' => 'Esbjerg', 'country' => 'Denmark'],
                            ['name' => 'Oslo', 'country' => 'Norway'],
                            ['name' => 'Odense', 'country' => 'Denmark'],
                            ['name' => 'Nynäshamn', 'country' => 'Sweden'],
                            ['name' => 'Örebro', 'country' => 'Sweden'],
                            ['name' => 'Linköping', 'country' => 'Sweden'],
                            ['name' => 'Malmö', 'country' => 'Sweden'],
                            ['name' => 'Stavanger', 'country' => 'Norway'],
                            ['name' => 'Södertälje', 'country' => 'Sweden'],
                            ['name' => 'Trelleborg', 'country' => 'Sweden'],
                            ['name' => 'Stockholm', 'country' => 'Sweden'],
                            ['name' => 'Växjö', 'country' => 'Sweden'],
                            ['name' => 'Västerås', 'country' => 'Sweden'],
                            ['name' => 'Uppsala', 'country' => 'Sweden'],
                        ],
                    ],
                    'Going East!' => [
                        'type' => MapType::DLC,
                        'locations' => [
                            ['name' => 'Košice', 'country' => 'Slovakia'],
                            ['name' => 'Kraków', 'country' => 'Poland'],
                            ['name' => 'Katowice', 'country' => 'Poland'],
                            ['name' => 'Gdańsk', 'country' => 'Poland'],
                            ['name' => 'Banská Bystrica', 'country' => 'Slovakia'],
                            ['name' => 'Białystok', 'country' => 'Poland'],
                            ['name' => 'Debrecen', 'country' => 'Hungary'],
                            ['name' => 'Budapest', 'country' => 'Hungary'],
                            ['name' => 'Ostrava', 'country' => 'Czech Republic'],
                            ['name' => 'Olsztyn', 'country' => 'Poland'],
                            ['name' => 'Łódź', 'country' => 'Poland'],
                            ['name' => 'Lublin', 'country' => 'Poland'],
                            ['name' => 'Warszawa', 'country' => 'Poland'],
                            ['name' => 'Pécs', 'country' => 'Hungary'],
                            ['name' => 'Szeged', 'country' => 'Hungary'],
                        ],
                    ],
                    'ProMods' => [
                        'type' => MapType::MOD,
                        // Source: https://www.google.com/maps/d/viewer?mid=1bDFpckQx-XAW1DP9Ip_GCmZEFHE
                        'locations' => [
                            ['name' => 'Antwerpen', 'country' => 'Belgium'],
                            ['name' => 'Croydon', 'country' => 'United Kingdom'],
                            ['name' => 'Portsmouth', 'country' => 'United Kingdom'],
                            ['name' => 'Flensburg', 'country' => 'Germany'],
                            ['name' => 'Burg auf Fehmarn', 'country' => 'Germany'],
                            ['name' => 'Padborg', 'country' => 'Denmark'],
                            ['name' => 'Helsinki ', 'country' => 'Finland'],
                            ['name' => 'Turku ', 'country' => 'Finland'],
                            ['name' => 'Hämeenlinna', 'country' => 'Finland'],
                            ['name' => 'Jyväskylä', 'country' => 'Finland'],
                            ['name' => 'Kuopio ', 'country' => 'Finland'],
                            ['name' => 'Lahti', 'country' => 'Finland'],
                            ['name' => 'Mikkeli', 'country' => 'Finland'],
                            ['name' => 'Porvoo', 'country' => 'Finland'],
                            ['name' => 'Tampere', 'country' => 'Finland'],
                            ['name' => 'Varkaus', 'country' => 'Finland'],
                            ['name' => 'Genova', 'country' => 'Italy'],
                            ['name' => 'Parma', 'country' => 'Italy'],
                            ['name' => 'Vicenza', 'country' => 'Italy'],
                            ['name' => 'Vaduz', 'country' => 'Liechtenstein'],
                            ['name' => 'Bayonne', 'country' => 'France'],
                            ['name' => 'Pau', 'country' => 'France'],
                            ['name' => 'Bad Oeynhausen', 'country' => 'Germany'],
                            ['name' => 'Oberhausen', 'country' => 'Germany'],
                            ['name' => 'Fort William', 'country' => 'United Kingdom'],
                            ['name' => 'Hull', 'country' => 'United Kingdom'],
                            ['name' => 'Inverness', 'country' => 'United Kingdom'],
                            ['name' => 'Oban', 'country' => 'United Kingdom'],
                            ['name' => 'Wick', 'country' => 'United Kingdom'],
                            ['name' => 'Basel', 'country' => 'Switzerland'],
                            ['name' => 'Akureyri', 'country' => 'Iceland'],
                            ['name' => 'Blönduós', 'country' => 'Iceland'],
                            ['name' => 'Borgarnes', 'country' => 'Iceland'],
                            ['name' => 'Keflavík Airport', 'country' => 'Iceland'],
                            ['name' => 'Reyðarfjörður', 'country' => 'Iceland'],
                            ['name' => 'Reykjavík', 'country' => 'Iceland'],
                            ['name' => 'Seyðisfjörður', 'country' => 'Iceland'],
                            ['name' => 'Vik', 'country' => 'Iceland'],
                            ['name' => 'Bologna', 'country' => 'Italy'],
                            ['name' => 'Ljubljana', 'country' => 'Slovenia'],
                            ['name' => 'Maribor', 'country' => 'Slovenia'],
                            ['name' => 'Pärnu', 'country' => 'Estonia'],
                            ['name' => 'Tallinn', 'country' => 'Estonia'],
                            ['name' => 'Tartu', 'country' => 'Estonia'],
                            ['name' => 'Valga', 'country' => 'Estonia'],
                            ['name' => 'Valka', 'country' => 'Latvia'],
                            ['name' => 'Modena', 'country' => 'Italy'],
                            ['name' => 'Europoort', 'country' => 'Netherlands'],
                            ['name' => 'Puttgarden', 'country' => 'Germany'],
                            ['name' => 'Thurso', 'country' => 'United Kingdom'],
                            ['name' => 'Rødbyhavn', 'country' => 'Denmark'],
                            ['name' => 'IJmuiden', 'country' => 'Netherlands'],
                            ['name' => 'Harwich', 'country' => 'United Kingdom'],
                            ['name' => 'Zwolle', 'country' => 'Netherlands'],
                            ['name' => 'Gävle', 'country' => 'Sweden'],
                            ['name' => 'Haparanda', 'country' => 'Sweden'],
                            ['name' => 'Karlstad', 'country' => 'Sweden'],
                            ['name' => 'Kristianstad', 'country' => 'Sweden'],
                            ['name' => 'Sundsvall', 'country' => 'Sweden'],
                            ['name' => 'Söderhamn', 'country' => 'Sweden'],
                            ['name' => 'Joensuu', 'country' => 'Finland'],
                            ['name' => 'Kärsämäki', 'country' => 'Finland'],
                            ['name' => 'Napapiiri', 'country' => 'Finland'],
                            ['name' => 'Oulu', 'country' => 'Finland'],
                            ['name' => 'Pori', 'country' => 'Finland'],
                            ['name' => 'Rovaniemi', 'country' => 'Finland'],
                            ['name' => 'Tornio', 'country' => 'Finland'],
                            ['name' => 'Vantaa', 'country' => 'Finland'],
                            ['name' => 'Viitasaari', 'country' => 'Finland'],
                            ['name' => 'Ulm', 'country' => 'Germany'],
                            ['name' => 'Chelmsford', 'country' => 'United Kingdom'],
                            ['name' => 'Herning', 'country' => 'Denmark'],
                            ['name' => 'Aarhus', 'country' => 'Denmark'],
                            ['name' => 'Holstebro', 'country' => 'Denmark'],
                            ['name' => 'Viborg', 'country' => 'Denmark'],
                            ['name' => 'Andorra la Vella', 'country' => 'Andorra'],
                            ['name' => 'Akranes', 'country' => 'Iceland'],
                            ['name' => 'Hólmavík', 'country' => 'Iceland'],
                            ['name' => 'Irun', 'country' => 'Spain'],
                            ['name' => 'San Sebastián', 'country' => 'Spain'],
                            ['name' => 'Narva', 'country' => 'Estonia'],
                            ['name' => 'Rīga', 'country' => 'Latvia'],
                            ['name' => 'Ventspils', 'country' => 'Latvia'],
                            ['name' => 'Kaunas', 'country' => 'Lithuania'],
                            ['name' => 'Panevėžys', 'country' => 'Lithuania'],
                            ['name' => 'Arad', 'country' => 'Romania'],
                            ['name' => 'Bacău', 'country' => 'Romania'],
                            ['name' => 'Baia Mare', 'country' => 'Romania'],
                            ['name' => 'București', 'country' => 'Romania'],
                            ['name' => 'Cluj-Napoca', 'country' => 'Romania'],
                            ['name' => 'Constanța', 'country' => 'Romania'],
                            ['name' => 'Craiova', 'country' => 'Romania'],
                            ['name' => 'Oradea', 'country' => 'Romania'],
                            ['name' => 'Piatra Neamț', 'country' => 'Romania'],
                            ['name' => 'Sibiu', 'country' => 'Romania'],
                            ['name' => 'Timișoara', 'country' => 'Romania'],
                            ['name' => 'Bălți', 'country' => 'Moldova'],
                            ['name' => 'Chișinău', 'country' => 'Moldova'],
                            ['name' => 'Русе (Ruse)', 'country' => 'Bulgaria'],
                            ['name' => 'Мукачеве (Mukacheve)', 'country' => 'Ukraine'],
                            ['name' => 'Ужгород (Uzhhorod)', 'country' => 'Ukraine'],
                            ['name' => 'Bielsko-Biała', 'country' => 'Poland'],
                            ['name' => 'Bydgoszcz', 'country' => 'Poland'],
                            ['name' => 'Cieszyn', 'country' => 'Poland'],
                            ['name' => 'Gdynia', 'country' => 'Poland'],
                            ['name' => 'Gorzów Wielkopolski', 'country' => 'Poland'],
                            ['name' => 'Grudziądz', 'country' => 'Poland'],
                            ['name' => 'Kielce', 'country' => 'Poland'],
                            ['name' => 'Koszalin', 'country' => 'Poland'],
                            ['name' => 'Krosno', 'country' => 'Poland'],
                            ['name' => 'Nowogard', 'country' => 'Poland'],
                            ['name' => 'Opole', 'country' => 'Poland'],
                            ['name' => 'Ostrołęka', 'country' => 'Poland'],
                            ['name' => 'Piła', 'country' => 'Poland'],
                            ['name' => 'Płock', 'country' => 'Poland'],
                            ['name' => 'Przemyśl', 'country' => 'Poland'],
                            ['name' => 'Radom', 'country' => 'Poland'],
                            ['name' => 'Rzeszów', 'country' => 'Poland'],
                            ['name' => 'Sanok', 'country' => 'Poland'],
                            ['name' => 'Siedlce', 'country' => 'Poland'],
                            ['name' => 'Suwałki', 'country' => 'Poland'],
                            ['name' => 'Świnoujście', 'country' => 'Poland'],
                            ['name' => 'Zamość', 'country' => 'Poland'],
                            ['name' => 'Klaksvík ', 'country' => 'Faroe Islands'],
                            ['name' => 'Tórshavn ', 'country' => 'Faroe Islands'],
                            ['name' => 'Kemi', 'country' => 'Finland'],
                            ['name' => 'Grödig', 'country' => 'Austria'],
                            ['name' => 'Krafla', 'country' => 'Iceland'],
                            ['name' => 'Selfoss', 'country' => 'Iceland'],
                            ['name' => 'Höfn', 'country' => 'Iceland'],
                            ['name' => 'Kolding', 'country' => 'Denmark'],
                            ['name' => 'Zgorzelec', 'country' => 'Poland'],
                            ['name' => 'Örnsköldsvik', 'country' => 'Sweden'],
                            ['name' => 'Umeå', 'country' => 'Sweden'],
                            ['name' => 'Kirkenes', 'country' => 'Norway'],
                            ['name' => 'Longyearbyen', 'country' => 'Svalbard and Jan Mayen'],
                            ['name' => 'Moskushamn', 'country' => 'Svalbard and Jan Mayen'],
                            ['name' => 'Alajärvi', 'country' => 'Finland'],
                            ['name' => 'Kemijärvi', 'country' => 'Finland'],
                            ['name' => 'Kristiinankaupunki', 'country' => 'Finland'],
                            ['name' => 'Vaasa', 'country' => 'Finland'],
                            ['name' => 'Narbonne', 'country' => 'France'],
                            ['name' => 'Perpignan', 'country' => 'France'],
                            ['name' => 'Aurach', 'country' => 'Germany'],
                            ['name' => 'Bremerhaven', 'country' => 'Germany'],
                            ['name' => 'Fürth', 'country' => 'Germany'],
                            ['name' => 'Halle (Saale)', 'country' => 'Germany'],
                            ['name' => 'Heilbronn', 'country' => 'Germany'],
                            ['name' => 'Birsay', 'country' => 'United Kingdom'],
                            ['name' => 'Broadford', 'country' => 'United Kingdom'],
                            ['name' => 'Evie', 'country' => 'United Kingdom'],
                            ['name' => 'Kirkwall', 'country' => 'United Kingdom'],
                            ['name' => 'Portree', 'country' => 'United Kingdom'],
                            ['name' => 'Stromness', 'country' => 'United Kingdom'],
                            ['name' => 'Douglas', 'country' => 'United Kingdom'],
                            ['name' => 'Ramsey', 'country' => 'Jersey'],
                            ['name' => 'Saint Helier', 'country' => 'Jersey'],
                            ['name' => 'Trinity', 'country' => 'Jersey'],
                            ['name' => 'Arnhem', 'country' => 'Netherlands'],
                            ['name' => 'Eindhoven', 'country' => 'Netherlands'],
                            ['name' => 'Brussel', 'country' => 'Belgium'],
                            ['name' => 'Firenze', 'country' => 'Italy'],
                            ['name' => 'Livorno', 'country' => 'Italy'],
                            ['name' => 'Barcelona', 'country' => 'Spain'],
                            ['name' => 'Bilbao', 'country' => 'Spain'],
                            ['name' => 'La Jonquera', 'country' => 'Spain'],
                            ['name' => 'Manresa', 'country' => 'Spain'],
                            ['name' => 'Haapsalu', 'country' => 'Estonia'],
                            ['name' => 'Kärdla', 'country' => 'Estonia'],
                            ['name' => 'Kuressaare', 'country' => 'Estonia'],
                            ['name' => 'Balvi', 'country' => 'Latvia'],
                            ['name' => 'Gulbene', 'country' => 'Latvia'],
                            ['name' => 'Liepāja', 'country' => 'Latvia'],
                            ['name' => 'Rēzekne', 'country' => 'Latvia'],
                            ['name' => 'Tukums', 'country' => 'Latvia'],
                            ['name' => 'Klaipėda', 'country' => 'Lithuania'],
                            ['name' => 'Bolungarvík', 'country' => 'Iceland'],
                            ['name' => 'Ísafjörður', 'country' => 'Iceland'],
                            ['name' => 'Зеленоградск (Zelenogradsk)', 'country' => 'Russia'],
                            ['name' => 'Мурманск (Murmansk)', 'country' => 'Russia'],
                            ['name' => 'Никель (Nikel)', 'country' => 'Russia'],
                            ['name' => 'Rakvere', 'country' => 'Estonia'],
                            ['name' => 'Jēkabpils', 'country' => 'Latvia'],
                            ['name' => 'Kolka', 'country' => 'Latvia'],
                            ['name' => 'Ogre', 'country' => 'Latvia'],
                            ['name' => 'Saldus', 'country' => 'Latvia'],
                        ],
                    ],
                    'RusMap' => [
                        'type' => MapType::MOD,
                        // Source: https://www.google.com/maps/d/viewer?mid=1bDFpckQx-XAW1DP9Ip_GCmZEFHE
                        'locations' => [
                            ['name' => 'Babruysk', 'country' => 'Belarus'],
                            ['name' => 'Baranovichi', 'country' => 'Belarus'],
                            ['name' => 'Brest', 'country' => 'Belarus'],
                            ['name' => 'Gomel', 'country' => 'Belarus'],
                            ['name' => 'Mogilev', 'country' => 'Belarus'],
                            ['name' => 'Mazyr', 'country' => 'Belarus'],
                            ['name' => 'Minsk', 'country' => 'Belarus'],
                            ['name' => 'Mstsislaw', 'country' => 'Belarus'],
                            ['name' => 'Orsha', 'country' => 'Belarus'],
                            ['name' => 'Pinsk', 'country' => 'Belarus'],
                            ['name' => 'Sluck', 'country' => 'Belarus'],
                            ['name' => 'Vitebsk', 'country' => 'Belarus'],
                            ['name' => 'Bryansk', 'country' => 'Russia'],
                            ['name' => 'Kaluga', 'country' => 'Russia'],
                            ['name' => 'Kholm', 'country' => 'Russia'],
                            ['name' => 'Klin', 'country' => 'Russia'],
                            ['name' => 'Luga', 'country' => 'Russia'],
                            ['name' => 'Moscow', 'country' => 'Russia'],
                            ['name' => 'Nevel', 'country' => 'Russia'],
                            ['name' => 'Obninsk', 'country' => 'Russia'],
                            ['name' => 'Ostashkov', 'country' => 'Russia'],
                            ['name' => 'Porkhov', 'country' => 'Russia'],
                            ['name' => 'Pskov', 'country' => 'Russia'],
                            ['name' => 'Roslavl', 'country' => 'Russia'],
                            ['name' => 'Rzhev', 'country' => 'Russia'],
                            ['name' => 'Saint Petersburg', 'country' => 'Russia'],
                            ['name' => 'Smolensk', 'country' => 'Russia'],
                            ['name' => 'Tver', 'country' => 'Russia'],
                            ['name' => 'Valday', 'country' => 'Russia'],
                            ['name' => 'Velikiye Luki', 'country' => 'Russia'],
                            ['name' => 'Veliky Novgorod', 'country' => 'Russia'],
                            ['name' => 'Velizh', 'country' => 'Russia'],
                            ['name' => 'Volokolamsk', 'country' => 'Russia'],
                            ['name' => 'Vyazma', 'country' => 'Russia'],
                            ['name' => 'Vyshny Volochyok', 'country' => 'Russia'],
                            ['name' => 'Yukhnov', 'country' => 'Russia'],
                            ['name' => 'Kursk', 'country' => 'Russia'],
                            ['name' => 'Orel', 'country' => 'Russia'],
                            ['name' => 'Tula', 'country' => 'Russia'],
                            ['name' => 'Voronezh', 'country' => 'Russia'],
                            ['name' => 'Vyborg', 'country' => 'Russia'],
                            ['name' => 'Shlisselburg', 'country' => 'Russia'],
                            ['name' => 'Kolomna', 'country' => 'Russia'],
                            ['name' => 'Tambov', 'country' => 'Russia'],
                            ['name' => 'Borisoglebsk', 'country' => 'Russia'],
                            ['name' => 'Volgograd', 'country' => 'Russia'],
                            ['name' => 'Volzhskiy', 'country' => 'Russia'],
                            ['name' => 'Krasnoslobodsk', 'country' => 'Russia'],
                        ],
                    ],
                ],
            ],
            'American Truck Simulator' => [
                // Source: http://truck-simulator.wikia.com/wiki/List_of_Cities_in_American_Truck_Simulator
                'maps' => [
                    'Default' => [
                        'type' => MapType::DEFAULT,
                        'locations' => [
                            ['name' => 'Bakersfield', 'country' => 'United States of America'],
                            ['name' => 'Barstow', 'country' => 'United States of America'],
                            ['name' => 'Carlsbad', 'country' => 'United States of America'],
                            ['name' => 'El Centro', 'country' => 'United States of America'],
                            ['name' => 'Eureka', 'country' => 'United States of America'],
                            ['name' => 'Fresno', 'country' => 'United States of America'],
                            ['name' => 'Hornbrook', 'country' => 'United States of America'],
                            ['name' => 'Huron', 'country' => 'United States of America'],
                            ['name' => 'Los Angeles', 'country' => 'United States of America'],
                            ['name' => 'Oakdale', 'country' => 'United States of America'],
                            ['name' => 'Oakland', 'country' => 'United States of America'],
                            ['name' => 'Oxnard', 'country' => 'United States of America'],
                            ['name' => 'Redding', 'country' => 'United States of America'],
                            ['name' => 'Sacramento', 'country' => 'United States of America'],
                            ['name' => 'San Diego', 'country' => 'United States of America'],
                            ['name' => 'San Francisco', 'country' => 'United States of America'],
                            ['name' => 'San Rafael', 'country' => 'United States of America'],
                            ['name' => 'Santa Cruz', 'country' => 'United States of America'],
                            ['name' => 'Santa Maria', 'country' => 'United States of America'],
                            ['name' => 'Stockton', 'country' => 'United States of America'],
                            ['name' => 'Truckee', 'country' => 'United States of America'],
                            ['name' => 'Ukiah', 'country' => 'United States of America'],
                            ['name' => 'Carson City', 'country' => 'United States of America'],
                            ['name' => 'Elko', 'country' => 'United States of America'],
                            ['name' => 'Ely', 'country' => 'United States of America'],
                            ['name' => 'Jackpot', 'country' => 'United States of America'],
                            ['name' => 'Las Vegas', 'country' => 'United States of America'],
                            ['name' => 'Pioche', 'country' => 'United States of America'],
                            ['name' => 'Primm', 'country' => 'United States of America'],
                            ['name' => 'Reno', 'country' => 'United States of America'],
                            ['name' => 'Tonopah', 'country' => 'United States of America'],
                            ['name' => 'Winnemucca', 'country' => 'United States of America'],
                        ],
                    ],
                    'Arizona' => [
                        'type' => MapType::DLC,
                        'locations' => [
                            ['name' => 'Camp Verde', 'country' => 'United States of America'],
                            ['name' => 'Ehrenberg', 'country' => 'United States of America'],
                            ['name' => 'Flagstaff', 'country' => 'United States of America'],
                            ['name' => 'Globe', 'country' => 'United States of America'],
                            ['name' => 'Grand Canyon Village', 'country' => 'United States of America'],
                            ['name' => 'Holbrook', 'country' => 'United States of America'],
                            ['name' => 'Kayenta', 'country' => 'United States of America'],
                            ['name' => 'Kingman', 'country' => 'United States of America'],
                            ['name' => 'Nogales', 'country' => 'United States of America'],
                            ['name' => 'Page', 'country' => 'United States of America'],
                            ['name' => 'Phoenix', 'country' => 'United States of America'],
                            ['name' => 'San Simon', 'country' => 'United States of America'],
                            ['name' => 'Show Low', 'country' => 'United States of America'],
                            ['name' => 'Sierra Vista', 'country' => 'United States of America'],
                            ['name' => 'Tucson', 'country' => 'United States of America'],
                            ['name' => 'Yuma', 'country' => 'United States of America'],
                        ],
                    ],
                ],
            ],
        ];
    }
}
